### PR TITLE
Milestone 6 : Friendships v2

### PR DESCRIPTION
**Pull request by macnick**
### In this milestone we did:

- Implement friendships with 2 rows for mutual friendship after confirmation
- Change the user timeline page to show all the recent posts from the current user and user's friends with.
- Implement integration test for confirming friendship

#### Please before testing do 
```
bundle install
rails db:create
rails db:migrate
rails db:seed
```
### Please review our code

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required
### Great work @macnick  and @addod19  :clap:  
**[REQUIRED]**
* We need to create a unique index using `user_id` and `friend_id` keys.
Currently when user A send a friend request to user B, user B can also be able to send a friend request to user A.
Look at [this](https://saheedoladele.com/blog/rails-unique-interchangeable-index-constraint/) tutorial in order to figure out how to set unique interchangeable index constraint.
* Let's correct all the linter errors.
* We have some failing tests. see :point_down: 
Screenshot from 2020-01-20 15-00-22

**After implementing the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by macnick** [comment]
Thank you Simon for your review. 
Regarding the friendships, if we implement the required change that means our Friendship table will have one record per friendship instead of two. Right?
Please let us know.

**Comment by wathigo** [comment]
Hi @macnick, 

Your are right.
With the unique constraint in place, it would be impossible to create an additional row upon friendship confirmation.
Another approach would be to restrict the views from displaying users with pending requests.
This way, it would be impossible to send a friend request to a user with pending request.

**Comment by wathigo** [comment]
Hi @macnick  and @addod19 ,

Sorry for misleading you in the first review.
I have confirmed that the `add friend` button is not displayed on users with pending request or users who are already friends.
Having an additional row upon friendship confirmation is also more efficient.
However some tests are still failing.
Let's fix that and submit another request for review.

**Comment by wathigo** [comment]
Hi @macnick ,

You are right.
Let's just update the views and hide the display of `add friend` to users with pending request or users who are already friends.

Thank you

**Comment by macnick** [comment]
Hi Simon, 

Here is a list of the changes: 

- The Friendships table uses two rows for friendships as per Milestone 5
- Button Add friend becomes Cancel Request if there is a friend request for this user
- Cancel Request cancels the friend request
- The Button Add friend does not appear on users that have sent a friend request to the current user.
- The user (receiver) that has a pending friend request cannot send a friend request, only to confirm the current on 
- Rewrote the test to work 

Please use a fresh db to do the tests. If you have the old on please do first
```
rails db:reset
rails db:seed
```

Please review our code. 

Nick

**Review by maelfosso — CHANGES_REQUESTED** [review]
# :wave: @macnick @addod19 

The requirements are all OK now. The only problem is the test. They all failed.
Screenshot from 2020-01-23 21-32-50

Kindly, correct the **users/sign_in** in the test and then submit a new code review request.
Thanks
**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

**Comment by macnick** [comment]
Hello Mael,

Thank you for your review. Unfortunately I can not duplicate the problem.
Did you run rails db:reset and rails db:seed before running the tests?
Here is a short video of my screen while running all the tests. Action
starts at 00:00:08

**Review by imhta — APPROVED** [review]
# Milestone approved 🎉 

### Hello  @macnick @addod19  , 👋 You have done a great job 👏 




----
### Happy coding 😄, You can move to next milestone 🏁  
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Comment by macnick** [comment]
Thank you ever so much. Great review!

**Pull request merged**
